#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2018-present, Lenovo. All rights reserved. 
# Licensed under BSD, see COPYING.BSD file for details.
#---------------------------------------------------------------------------


source ${BMC_TOPDIR}/sdk/environment-setup-i686-linux-gnueabi
export BMC_SDK="elie"

Color_Off='\e[0m'
IYellow='\e[0;93m'
On_Blue='\e[44m'

echo -e " ${IYellow}${On_Blue}-> Preloading SDK: $BMC_SDK <-${Color_Off}"

make $@

